services:
  hookappd-back-api:
    platform: linux/amd64
    build:
      context: src
      target: builder
    container_name: hookappd-back-api
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://hookappd:hookappd@hookappd-db:5432/hookappd
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./src/:/hookappd-back-api
    networks:
      - hookappd
  hookappd-db:
    container_name: hookappd-db
    image: postgres:15
    environment:
      POSTGRES_USER: hookappd
      POSTGRES_PASSWORD: hookappd
      PGDATA: /data/postgres
      POSTGRES_DB: hookappd
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hookappd
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: hookappd
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - hookappd

networks:
  hookappd:
    driver: bridge

volumes:
    postgres:
    pgadmin: